(source gnu)
(source melpa)
(source org)

(depends-on "ace-window")
(depends-on "alchemist")
(depends-on "auto-compile")
(depends-on "avy")
(depends-on "bind-key")
(depends-on "company-mode")
(depends-on "emojify")
(depends-on "elixir-mode")
(depends-on "fold-dwim")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-ls-git")
(depends-on "hydra")
(depends-on "initsplit")
(depends-on "key-chord")
(depends-on "lispy")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "org")
(depends-on "org-plus-contrib")
(depends-on "pallet")
(depends-on "smart-tabs-mode")
(depends-on "spaceline")
(depends-on "swiper-helm")
(depends-on "use-package")
(depends-on "which-key")
;;;pallet-ignore
(depends-on "info-lookmore" :git "https://github.com/emacsmirror/info-lookmore")
(depends-on "info+" :git "https://github.com/emacsmirror/info-plus")
(depends-on "solarized" :git "https://github.com/sellout/emacs-color-theme-solarized")
