#+TITLE: Custom Settings

This is all the stuff that doesn't fit in the other settings
files. Nothing fancy I'm afraid.

* Emacs
** UI Changes
*** GUI
   The mouse is the devil in emacs. Someday I'll figure out how to get
   rid of the damn thing entirely. It'll be beautiful, lemme tell you.
#+BEGIN_SRC emacs-lisp
  (tooltip-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (setq inhibit-startup-screen t
        use-dialog-box nil)
  (if (version< emacs-version "25")
      (scroll-bar-mode -1)
    (menu-bar-no-scroll-bar))
#+END_SRC
*** Font
   Source Code Pro
   [[http://adobe-fonts.github.io/source-code-pro/]]
   Meslo LG S
   [[https://github.com/andreberg/Meslo-Font]] 
#+BEGIN_SRC emacs-lisp
  (if (version< emacs-version "25")
      (progn
        (set-fontset-font "fontset-default"
                          'ascii
                          (font-spec :name "Fira Code"
                                     :weight 'normal :width 'normal
                                     :size 9.0)
                          nil 'prepend)
      (set-frame-font "fontset-default")))
#+END_SRC
** Backups
   emacs likes to strew backup and autosave files everywhere. They
   ought to be in one place. So let's do that.
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist `(("." . ,(concat user-emacs-directory "backups")))
        auto-save-file-name-transforms `((".*" ,(concat user-emacs-directory
                                                        "auto-save-list/") t)))
#+END_SRC
   I habitually use version control so I don't need many backups and I
   don't care if I don't have old ones around.
#+BEGIN_SRC emacs-lisp
  (setq delete-old-versions t
        kept-old-versions 0
        kept-new-versions 5
        version-control t
        vc-make-backup-files t
        backup-by-copying t)
#+END_SRC
** Mode line
   My mode line edits got a little out of hand.
#+BEGIN_SRC emacs-lisp
  (use-package nkc-mode-line)
#+END_SRC
** Directory names
   whatbox mounts home directories in /mnt which is inaccessible to users
   and screws up emacs sometimes.
#+BEGIN_SRC emacs-lisp
  (setq directory-abbrev-alist '(("/mnt/sd[a-z][0-9]" . "/home")))
#+END_SRC
* Settings
** Visual line mode
#+BEGIN_SRC emacs-lisp
  (visual-line-mode)
#+END_SRC
** Backward Kill Word
#+BEGIN_SRC emacs-lisp
  (bind-key "C-w" 'backward-kill-word)
#+END_SRC
** Indent with spaces only
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC
* Provide
#+BEGIN_SRC emacs-lisp
  (provide 'nkc-settings)
#+END_SRC
